/*
MIT License

Copyright (c) 2016-2019 Andrés Castellanos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
package viper.syntax;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>syntax/lexer.flex</tt>
 */
public final class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int STRING = 4;
  public static final int SBACKSLASH = 6;
  public static final int CLEAN = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /**
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED =
    "\11\0\1\47\1\43\1\45\1\45\1\44\22\0\1\47\1\16\1\41"+
    "\1\46\1\0\1\0\1\0\1\41\1\1\1\2\1\12\1\10\1\6"+
    "\1\11\1\0\1\13\12\37\1\3\1\7\1\14\1\15\3\0\32\40"+
    "\1\0\1\42\2\0\1\40\1\0\1\36\1\25\1\40\1\17\1\20"+
    "\1\21\1\40\1\34\1\22\2\40\1\27\1\40\1\23\1\26\2\40"+
    "\1\31\1\30\1\24\1\35\1\32\1\33\3\40\1\4\1\0\1\5"+
    "\7\0\1\45\u1fa2\0\1\45\1\45\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\13\20\1\21\1\22\2\23\1\24\1\25\2\26\1\27"+
    "\1\30\1\31\2\32\1\33\2\34\1\25\1\35\1\36"+
    "\3\20\1\37\7\20\1\40\2\20\1\41\2\20\1\42"+
    "\3\20\1\43\1\20\1\44\1\45\1\20\1\46\1\20"+
    "\1\47\1\20\1\50\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\310\0\310"+
    "\0\310\0\310\0\310\0\310\0\310\0\360\0\360\0\310"+
    "\0\310\0\u0118\0\u0140\0\310\0\u0168\0\u0190\0\u01b8\0\u01e0"+
    "\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\360"+
    "\0\310\0\310\0\u0320\0\310\0\310\0\310\0\u0348\0\310"+
    "\0\310\0\310\0\310\0\u0370\0\310\0\310\0\u0398\0\u03c0"+
    "\0\310\0\310\0\u03e8\0\u0410\0\u0438\0\u0208\0\u0460\0\u0488"+
    "\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0208\0\u0578\0\u05a0"+
    "\0\u0208\0\u05c8\0\u05f0\0\u0208\0\u0618\0\u0640\0\u0668\0\u0208"+
    "\0\u0690\0\u0208\0\u0208\0\u06b8\0\u0208\0\u06e0\0\u0208\0\u0708"+
    "\0\u0208\0\u0208";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\2\31\1\34"+
    "\1\35\1\36\1\37\3\31\1\40\1\31\1\41\1\6"+
    "\1\42\1\43\1\42\1\44\1\42\43\45\1\46\1\47"+
    "\1\46\2\45\41\50\1\51\1\52\1\53\1\54\1\53"+
    "\2\50\43\55\1\56\1\57\1\56\2\55\41\45\1\46"+
    "\2\45\1\60\3\45\107\0\1\40\25\0\1\61\47\0"+
    "\1\62\51\0\1\31\1\63\20\31\26\0\10\31\1\64"+
    "\11\31\26\0\17\31\1\65\2\31\26\0\2\31\1\66"+
    "\1\31\1\67\15\31\26\0\22\31\26\0\12\31\1\70"+
    "\7\31\26\0\7\31\1\71\12\31\26\0\5\31\1\72"+
    "\14\31\26\0\1\31\1\73\20\31\26\0\7\31\1\74"+
    "\12\31\26\0\15\31\1\75\4\31\52\0\1\42\47\0"+
    "\1\46\47\0\1\53\47\0\1\56\47\0\1\45\23\0"+
    "\2\31\1\76\17\31\26\0\11\31\1\77\10\31\26\0"+
    "\10\31\1\100\11\31\26\0\5\31\1\101\14\31\26\0"+
    "\16\31\1\102\3\31\26\0\7\31\1\103\12\31\26\0"+
    "\12\31\1\104\7\31\26\0\5\31\1\105\14\31\26\0"+
    "\3\31\1\106\16\31\26\0\3\31\1\107\16\31\26\0"+
    "\1\31\1\110\20\31\26\0\11\31\1\111\10\31\26\0"+
    "\1\31\1\112\20\31\26\0\10\31\1\113\11\31\26\0"+
    "\16\31\1\114\3\31\26\0\1\115\21\31\26\0\10\31"+
    "\1\116\11\31\26\0\1\31\1\117\20\31\26\0\12\31"+
    "\1\120\7\31\26\0\1\31\1\121\20\31\26\0\4\31"+
    "\1\122\15\31\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1840];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\10\11\2\1\2\11\2\1\1\11\14\1\2\11"+
    "\1\1\3\11\1\1\4\11\1\1\2\11\2\1\2\11"+
    "\40\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the
   * matched text
   */
  private int yycolumn;

  /**
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /**
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

  /** string length */
  private int length;

  /** strings and chars string builder */
  private StringBuilder text;

  /**
   * Creates a new symbol with default value.
   *
   * @param type symbol id
   * @return a symbol
   */
  private Symbol symbol(int type) {
    return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
  }

  /**
   * Creates a new symbol with a given value.
   *
   * @param type symbol id
   * @param value symbol value
   * @return a symbol
   */
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline + 1, yycolumn + 1, value);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    length = 0;
  text = new StringBuilder(0);
    this.zzReader = in;
  }


  /**
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   switch (yystate()) {
    case STRING:
      return symbol(Token.ERROR, "EOF in string constant");
    case SBACKSLASH:
      return symbol(Token.ERROR, "EOF in string constant");
    default:
      return symbol(Token.EOF);
  }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(Token.ERROR, "invalid language element: '" + yytext() + "'");
            }
            // fall through
          case 42: break;
          case 2:
            { return symbol(Token.LPAREN);
            }
            // fall through
          case 43: break;
          case 3:
            { return symbol(Token.RPAREN);
            }
            // fall through
          case 44: break;
          case 4:
            { return symbol(Token.COLON);
            }
            // fall through
          case 45: break;
          case 5:
            { return symbol(Token.LBRACE);
            }
            // fall through
          case 46: break;
          case 6:
            { return symbol(Token.RBRACE);
            }
            // fall through
          case 47: break;
          case 7:
            { return symbol(Token.COMMA);
            }
            // fall through
          case 48: break;
          case 8:
            { return symbol(Token.SEMI);
            }
            // fall through
          case 49: break;
          case 9:
            { return symbol(Token.PLUS);
            }
            // fall through
          case 50: break;
          case 10:
            { return symbol(Token.MINUS);
            }
            // fall through
          case 51: break;
          case 11:
            { return symbol(Token.TIMES);
            }
            // fall through
          case 52: break;
          case 12:
            { return symbol(Token.DIV);
            }
            // fall through
          case 53: break;
          case 13:
            { return symbol(Token.LT);
            }
            // fall through
          case 54: break;
          case 14:
            { return symbol(Token.ASSIGN);
            }
            // fall through
          case 55: break;
          case 15:
            { return symbol(Token.NOT);
            }
            // fall through
          case 56: break;
          case 16:
            { return symbol(Token.ID);
            }
            // fall through
          case 57: break;
          case 17:
            { return symbol(Token.INTEGER);
            }
            // fall through
          case 58: break;
          case 18:
            { length = 0;
    text.setLength(0);
    yybegin(STRING);
            }
            // fall through
          case 59: break;
          case 19:
            { /* do nothing */
            }
            // fall through
          case 60: break;
          case 20:
            { yybegin(COMMENT);
            }
            // fall through
          case 61: break;
          case 21:
            { /* consume everything */
            }
            // fall through
          case 62: break;
          case 22:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 63: break;
          case 23:
            { length++;
    text.append(yytext());
            }
            // fall through
          case 64: break;
          case 24:
            { yybegin(YYINITIAL);
    String str = text.toString();
    if (length > 1024) {
      return symbol(Token.ERROR, "string constant too long");
    }
    return symbol(Token.STRING, str);
            }
            // fall through
          case 65: break;
          case 25:
            { yybegin(SBACKSLASH);
    text.append('\\');
            }
            // fall through
          case 66: break;
          case 26:
            { yybegin(CLEAN);
    return symbol(Token.ERROR, "unterminated string constant");
            }
            // fall through
          case 67: break;
          case 27:
            { length++;
    text.append(yytext());
    yybegin(STRING);
            }
            // fall through
          case 68: break;
          case 28:
            { length++;
    text.append("n");
    yybegin(STRING);
            }
            // fall through
          case 69: break;
          case 29:
            { return symbol(Token.LE);
            }
            // fall through
          case 70: break;
          case 30:
            { return symbol(Token.EQ);
            }
            // fall through
          case 71: break;
          case 31:
            { return symbol(Token.IF);
            }
            // fall through
          case 72: break;
          case 32:
            { return symbol(Token.DEF);
            }
            // fall through
          case 73: break;
          case 33:
            { return symbol(Token.INT);
            }
            // fall through
          case 74: break;
          case 34:
            { return symbol(Token.STR);
            }
            // fall through
          case 75: break;
          case 35:
            { return symbol(Token.ELSE);
            }
            // fall through
          case 76: break;
          case 36:
            { return symbol(Token.BOOLEAN, true);
            }
            // fall through
          case 77: break;
          case 37:
            { return symbol(Token.BOOL);
            }
            // fall through
          case 78: break;
          case 38:
            { return symbol(Token.VOID);
            }
            // fall through
          case 79: break;
          case 39:
            { return symbol(Token.BOOLEAN, false);
            }
            // fall through
          case 80: break;
          case 40:
            { return symbol(Token.WHILE);
            }
            // fall through
          case 81: break;
          case 41:
            { return symbol(Token.RETURN);
            }
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
